[tool.poetry]
name = "depth-image-annotator"
version = "0.1.0"
description = ""
authors = ["František Kmječ <frantisek.kmjec@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
